# url=http://justo-staging.orientaloutsourcing.in/
# username=justo-dev@satgurutechnologies.com
# password=Bhawan@stag@2026#


url=https://kits-staging.kingit.com.au/index.php
username=bhawan@kingit.com.au
password=W7z@pB!r9Tq#Lx2V